// leetcode No.389 Find the Difference

/*
 *	Given two strings s and t which consist of only lowercase letters.
 *	String t is generated by random shuffling string s and then add one more letter at a random position.
 *	Find the letter that was added in t.
 */

#include "includelib.h"

char findTheDifference(string s, string t)
{
	unordered_map<char, int> bin(t.size());
	size_t pos(0);
	for (;pos != s.size();++pos)
	{
		++bin[s[pos]];
		++bin[t[pos]];
	}
	++bin[t[pos]];
	for (auto index : bin)
	{
		//随机添加的字母有可能是出现过的字母
		if (index.second % 2 == 1) return index.first;
	}
}

//也可以直接用XOR来做，速度更快